version: "3.8"
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    container_name: laravel-php
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - .:/var/www/html
    container_name: laravel-nginx
    depends_on:
      - php-fpm